on:
  push:
    branches: [ master,release_branch* ]
  pull_request:
    branches: [ master,release_branch* ]
  workflow_dispatch:

permissions: read-all

jobs:
  build-linux:
    if: github.repository_owner == 'oneapi-src'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: hendrikmuhs/ccache-action@v1
      - name: Build Loader on Latest Ubuntu
        run: |
          mkdir build
          cd build
          cmake \
            -D CMAKE_C_COMPILER_LAUNCHER=ccache \
            -D CMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -D CMAKE_BUILD_TYPE=Release \
            -D BUILD_L0_LOADER_TESTS=1 \
            ..
          make -j$(nproc)
      - env:
          ZE_ENABLE_LOADER_DEBUG_TRACE: '1'
          ZEL_LIBRARY_PATH: '${{ github.workspace }}/build/lib'
        working-directory: build
        run: ctest -V

  build-windows:
    if: github.repository_owner == 'oneapi-src'
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build Loader on Latest Windows
        run: |
          mkdir build
          cd build
          cmake -D BUILD_L0_LOADER_TESTS=1 ..
          cmake --build . --config Release
      - env:
          ZE_ENABLE_LOADER_DEBUG_TRACE: '1'
          ZEL_LIBRARY_PATH: '${{ github.workspace }}/build/bin/Release'
        working-directory: build
        run: ctest -C Release -V
